/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.jros;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int arrow=0x7f020000;
        public static final int arrow_down_float=0x7f020001;
        public static final int icon=0x7f020002;
    }
    public static final class id {
        public static final int Edit=0x7f06000b;
        public static final int complete=0x7f06000a;
        public static final int delete=0x7f060009;
        public static final int detail=0x7f060006;
        public static final int dicon=0x7f060005;
        public static final int icon=0x7f060007;
        public static final int location=0x7f060008;
        public static final int options=0x7f060001;
        public static final int save=0x7f060004;
        public static final int spinner=0x7f060003;
        public static final int task=0x7f060002;
        public static final int taskList=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int row=0x7f030001;
    }
    public static final class menu {
        public static final int option=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
